title = "Explorer Kura"

gitSourceBranch = "main"
changelog = true
classOrder = [
    "QuickAction"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

tagline = "A replacement for Roblox's Classroom Mode."

[footer]
style = "dark"
copyright = "Copyright © 2022 Explorers of the Metaverse. Built with Moonwave and Docusaurus"

[[navbar.items]]
href = "https://guilded.gg/ScratcherStudios"
label = "Guilded"
position = "right"

[[footer.links]]
title = "Support"

[[footer.links.items]]
label = "Scratcher Studios Guilded"
href = "https://guilded.gg/ScratcherStudios/"

[[footer.links.items]]
label = "Explorers of the Metaverse Discord"
href = "https://discord.gg/7NmeNfNPR7"

[[footer.links]]
title = "Installation"

[[footer.links.items]]
label = "GitHub"
href = "https://github.com/Scratcher-Studios/Explorer-Kura/releases"

[[footer.links.items]]
label = "Roblox Model"
href = "https://roblox.com/"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "A sleek user interface"
description = "A modern, easy to use user interface for the future of classrooms."

[[home.features]]
title = "Extensibility for Educators and Developers"
description = "Give educators the control the experience to suit the students needs with the QuickAction API."

[[home.features]]
title = "Free, Open, Connected."
description = "No cost to educator or developer, with greater featuresets in the works."