title = "Explorer Kura"

gitSourceBranch = "main"
changelog = true
classOrder = [
    "QuickAction"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "https://raw.githubusercontent.com/Scratcher-Studios/Explorer-Kura/main/.moonwave/favicon.png"
[[themeConfig]]
[[themeConfig.navbar]]
title = 'Explorer Kura'
[[themeConfig.navbar.logo]]
alt = 'Explorer Kura Logo'
src = 'https://github.com/Scratcher-Studios/Explorer-Kura/blob/main/.moonwave/logoblack.png'
srcDark = 'https://raw.githubusercontent.com/Scratcher-Studios/Explorer-Kura/main/.moonwave/Logo.png'
href = 'https://scratcher-studios.github.io/Explorer-Kura/'
target = '_self'
width = 244.625
height = 64

tagline = "A replacement for Roblox's Classroom Mode."

[footer]
style = "dark"
copyright = "Copyright © 2022 Explorers of the Metaverse. Built with Moonwave and Docusaurus"

[[navbar.items]]
href = "https://guilded.gg/ScratcherStudios"
label = "Guilded"
position = "right"

[[footer.links]]
title = "Support"

[[footer.links.items]]
label = "Scratcher Studios Guilded"
href = "https://guilded.gg/ScratcherStudios/"

[[footer.links.items]]
label = "Explorers of the Metaverse Discord"
href = "https://discord.gg/7NmeNfNPR7"

[[footer.links]]
title = "Installation"

[[footer.links.items]]
label = "GitHub"
href = "https://github.com/Scratcher-Studios/Explorer-Kura/releases"

[[footer.links.items]]
label = "Roblox Model"
href = "https://roblox.com/"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "A sleek user interface"
description = "A modern, easy to use user interface for the future of classrooms."
image = "https://raw.githubusercontent.com/Scratcher-Studios/Explorer-Kura/main/.moonwave/gui.svg"

[[home.features]]
title = "Extensibility for Educators and Developers"
description = "Give educators the control the experience to suit the students needs with the QuickAction API."
image = "https://raw.githubusercontent.com/Scratcher-Studios/Explorer-Kura/main/.moonwave/buildingblocks.svg"

[[home.features]]
title = "Free, Open, Connected."
description = "No cost to educator or developer, with greater featuresets in the works."
image = "https://raw.githubusercontent.com/Scratcher-Studios/Explorer-Kura/main/.moonwave/co-operation.svg"